### ISSUE TITLE
PAML: conflicting md5 sum

### ISSUE THREAD

**Issue by kloetzl** [reedacartwright/archinformatics#1]
Hi,

I just tried to install PAML, but it fails the validity check. My md5sum is `ac5a062bfea1f4eaac79008434030acf`.

Best,
Fabian

**Comment by reedacartwright** [comment]
Hmm, what is the size of your file?  You might have a truncated download.

**Comment by reedacartwright** [comment]
Nevermind, I just confirmed the md5sum has changed.
